import {createHash} from 'node:crypto'
export const SOURCE='thestyerteam_outbound'
export const MAILBOX='adam@thestyerteam.com'
export const GRAPH_FOLDER='https://graph.microsoft.com/v1.0/me/mailFolders/sentitems/messages'
const FIELDS='id,internetMessageId,subject,sentDateTime,from,toRecipients,ccRecipients,conversationId,webLink,hasAttachments,isDraft'
export function graphPageUrl(from:string,until:string,next:string|null){if(next){const u=new URL(next);if(u.origin!=='https://graph.microsoft.com'||!/^\/v1\.0\/(?:me|users\/[^/]+)\/mailFolders(?:\/(?:sentitems|SentItems)|\('(?:sentitems|SentItems)'\))\/messages$/.test(u.pathname))throw Error('Unsupported source page');return u.href}const u=new URL(GRAPH_FOLDER);u.searchParams.set('$select',FIELDS);u.searchParams.set('$filter',`sentDateTime ge ${new Date(from).toISOString()} and sentDateTime lt ${new Date(until).toISOString()}`);u.searchParams.set('$orderby','sentDateTime asc');u.searchParams.set('$top','100');return u.href}
type Message={id?:string;internetMessageId?:string;subject?:string;sentDateTime?:string;from?:{emailAddress?:{address?:string}};toRecipients?:{emailAddress?:{address?:string}}[];ccRecipients?:{emailAddress?:{address?:string}}[];webLink?:string;hasAttachments?:boolean;isDraft?:boolean}
export function normalizeOutbound(message:Message){if(message.isDraft||message.from?.emailAddress?.address?.toLowerCase()!==MAILBOX)return null;const when=Date.parse(message.sentDateTime||'');if(!Number.isFinite(when)||!message.id)throw Error('Message identity or source date missing');const recipients=[...new Set([...(message.toRecipients||[]),...(message.ccRecipients||[])].map(x=>x.emailAddress?.address?.toLowerCase().trim()).filter((x):x is string=>!!x&&x!==MAILBOX))].slice(0,100);const key=createHash('sha256').update(message.internetMessageId?.trim()||`graph:${message.id}`).digest('hex');const subject=String(message.subject||'Outbound email').slice(0,500);const held=/\b\d{3}-\d{2}-\d{4}\b|social security|tax return|bank statement|credit report|passport|driver.?s license/i.test(subject);const url=String(message.webLink||'');const validLink=/^https:\/\/(?:outlook\.office\.com|outlook\.office365\.com|outlook\.live\.com)\//i.test(url)?url:null;return {event_key:key,occurred_at:new Date(when).toISOString(),recipients,payload:{subject:held?'Sensitive subject held; open the source email':subject,metadata:{webLink:validLink,hasAttachments:!!message.hasAttachments,direction:'outbound',authorship:'unverified',internetMessageId:message.internetMessageId||null}},held:{subject:'Unmatched sent-mail reference',metadata:{webLink:validLink,hasAttachments:!!message.hasAttachments,direction:'outbound',authorship:'unverified'}}}}
export function outboundDisplay(payload:Record<string,unknown>){const metadata=payload.metadata&&typeof payload.metadata==='object'?payload.metadata as Record<string,unknown>:{};const url=typeof metadata.webLink==='string'?metadata.webLink:'';return {subject:typeof payload.subject==='string'?payload.subject:'Outbound email reference',source_url:/^https:\/\/(?:outlook\.office\.com|outlook\.office365\.com|outlook\.live\.com)\//i.test(url)?url:null}}
