import {describe,it,expect} from 'vitest';
import {normalizeAriveRows,matchAriveLead} from './arive-sync';
import {deskRows,deskTotals,workingStage} from './simple-desk';
import type {Snapshot} from './types';
const raw={ariveLoanId:12345678,modifiedDateTime:'2026-09-05T10:24:30.123Z',loanOriginatorEmail:'adam.styer@hypersmart.loan',currentLoanStatus_status:'PREAPPROVED',baseLoanAmount:540000,financedFees:0,loanBorrower1_firstName:'Sample',loanBorrower1_lastName:'Borrower',loanBorrower1_emailAddressText:'sample@example.test'};
const fact=()=>normalizeAriveRows({rows:[raw],count:1},Date.parse('2026-09-05T12:00:00Z'))[0];
describe('ARIVE reconciliation',()=>{
 it('retains time precision and calculates total from base plus known financed fees',()=>{expect(fact()).toMatchObject({source_updated_at:raw.modifiedDateTime,loan_amount:540000});expect(normalizeAriveRows({rows:[{...raw,financedFees:9000}],count:1})[0].loan_amount).toBe(549000);expect(normalizeAriveRows({rows:[{...raw,financedFees:null}],count:1})[0].loan_amount).toBeNull();});
 it('rejects incomplete pages, duplicate IDs, invalid times and excludes unrelated originators',()=>{expect(()=>normalizeAriveRows({rows:[raw],count:2})).toThrow();expect(()=>normalizeAriveRows({rows:[raw,raw],count:2})).toThrow();expect(()=>normalizeAriveRows({rows:[{...raw,modifiedDateTime:'2026-09-05'}],count:1})).toThrow();expect(normalizeAriveRows({rows:[{...raw,loanOriginatorEmail:'someone@example.test'}],count:1})).toEqual([]);});
 it('requires identity corroboration, handles nicknames using email and surname, and flags multiple scenarios',()=>{const f=fact();expect(matchAriveLead({name:'Different Borrower',originalLoan:'12345678'},[f],'now').state).toBe('review');expect(matchAriveLead({name:'Sam Borrower',email:'SAMPLE@example.test'},[f],'now').state).toBe('matched');expect(matchAriveLead({name:'Sample Borrower',email:raw.loanBorrower1_emailAddressText},[f,{...f,arive_loan_id:'98765432'}],'now').state).toBe('review');expect(matchAriveLead({name:'Sample Borrower',previous:{state:'matched',ids:['12345678'],reason:'verified',checked_at:'before'}},[{...f,arive_loan_id:'98765432'}],'now').state).toBe('review');});
 it('uses verified loan facts over stale notes and keeps user notes, referral and acquisition source',()=>{const f=fact();const s={asOf:'now',contacts:[],inquiries:[],loans:[],links:[],tasks:[],members:[],health:[],ariveFacts:[f],preferences:[{id:'p',status:'Lead Contacted',amount_note:'405000',notes:'Keep these notes',referral_name:'Carson Handy',reporting_source:'AI',provenance:{restored_lead:{name:'Sample Borrower',loan:'12345678',planning_volume:405000}}}]} as unknown as Snapshot;const row=deskRows(s)[0];expect(row).toMatchObject({stage:'Pre-approved',amount:540000,notes:'Keep these notes',referral:'Carson Handy',source:'AI',ariveOwned:true});expect(deskTotals([row]).compensation).toBe(10800);s.ariveFacts=[{...f,loan_amount:null}];expect(deskRows(s)[0].amount).toBeNull();});
 it('does not turn application intake or prequalification into preapproval',()=>{expect(workingStage('APPLICATION_INTAKE')).toBe('Application Started');expect(workingStage('Prequalified')).toBe('Application Started');expect(workingStage('PREAPPROVED')).toBe('Pre-approved');for(const s of ['DISCLOSURE_SENT','LOAN_SETUP','RE_SUBMITTAL','APPROVED_WITH_CONDITION'])expect(workingStage(s)).toBe('Loan in Process');expect(workingStage('ADVERSE')).toBe('Archived/not qualified');});
});
