import { describe, it, expect } from 'vitest';
import { buildRows, cohortMetrics, periodEvents, rowTotals, filterRows, day, loanSignals, operationalMetrics, cohortGroups, fundedPeriodTotals } from './model';
import { ALL_FILTERS, type Snapshot, type Inquiry, type Loan, type Milestone, type Task, type Contact } from './types';
const inquiry = (id: string, received_at = '2026-08-10T16:00:00Z', contact_id = 'c1') => ({ id, contact_id, received_at, legitimacy: 'inquiry', is_test: false, source: 'Website', owner_id: 'owner', provenance: {} } as Inquiry);
const loan = (id: string, amount: number | null = 100000, status = 'LOAN_FUNDED') => ({ id, contact_id: 'c1', loan_amount: amount, status, operational_owner_id: 'owner' } as Loan);
const milestone = (id: string, loan_id: string | null, milestone: string, occurred_at = '2026-09-04T16:00:00Z', inquiry_id: string | null = null) => ({ id, loan_id, inquiry_id, milestone, occurred_at, voided_at: null, evidence: {}, source: 'ARIVE' } as Milestone);
function fixture(): Snapshot { return { asOf: '2026-09-05T04:00:00Z', viewerId: 'owner', organizationId: 'org', members: [{ id: 'owner', full_name: 'Adam', email: 'adam@example.com', role: 'owner' }], contacts: [{ id: 'c1', first_name: 'Internal', last_name: 'Fixture', operational_owner_id: 'owner' } as Contact], inquiries: [inquiry('i1'), inquiry('i2', '2026-08-20T16:00:00Z')], loans: [loan('l1'), loan('l2', 200000)], links: [{ id: 'a', inquiry_id: 'i1', loan_id: 'l1', reviewed_at: '2026-09-04T16:00:00Z', evidence: 'Reviewed source' }, { id: 'b', inquiry_id: 'i1', loan_id: 'l2', reviewed_at: '2026-09-04T16:00:00Z', evidence: 'Reviewed source' }], milestones: [milestone('m1', 'l1', 'application_started', '2026-08-11T16:00:00Z'), milestone('m2', 'l1', 'preapproval_issued'), milestone('m3', 'l1', 'funded'), milestone('m4', 'l2', 'funded')], compensation: [{ loan_id: 'l1', gross_source: 'arive', gross_comp: 3000, net_comp: 2500, payout_status: 'pending' }, { loan_id: 'l2', gross_source: 'manual', gross_comp: 4000, net_comp: 3500, payout_status: 'pending' }], tasks: [], preferences: [], activity: [], health: [], delivery: [] }; }
const august = { ...ALL_FILTERS, from: '2026-08-01', to: '2026-08-31' };
describe('evidence-based operating metrics', () => {
    it('follows an acquisition cohort through later funding and counts a lead once for two loans', () => { const c = cohortMetrics(fixture(), august); expect(c.leads).toHaveLength(2); expect(c.people).toBe(1); expect(c.repeats).toBe(1); expect(c.funded).toEqual(['i1']); expect(c.revenue).toBe(7000); expect(c.revenuePerLead).toBe(3500); expect(c.ratios.at(-1)).toMatchObject({ numerator: 1, denominator: 2, rate: .5 }); expect(c.unlinked).toBe(1); });
    it('does not count current-period funding against current-period acquired leads', () => { const c = cohortMetrics(fixture(), { ...august, from: '2026-09-01', to: '2026-09-30' }); expect(c.leads).toHaveLength(0); expect(c.ratios.at(-1)?.rate).toBeNull(); expect(periodEvents(fixture(), { ...august, from: '2026-09-01', to: '2026-09-30' }).filter(m => m.milestone === 'funded')).toHaveLength(2); });
    it('never attributes a loan by matching the person alone', () => { const s = fixture(); s.links = []; expect(cohortMetrics(s, august).funded).toHaveLength(0); expect(cohortMetrics(s, august).unlinked).toBe(2); });
    it('excludes test, continuation and held identities from conversion denominators', () => { const s = fixture(); s.inquiries.push({ ...inquiry('test'), is_test: true }, { ...inquiry('review'), legitimacy: 'review' }, { ...inquiry('followup'), legitimacy: 'continuation' }); expect(cohortMetrics(s, august).leads).toHaveLength(2); expect(cohortMetrics(s, august).held).toBe(1); });
    it('uses corrected active dates and deduplicates repeated milestone events', () => { const s = fixture(); s.milestones[2].voided_at = '2026-09-05T01:00:00Z'; s.milestones.push(milestone('corrected', 'l1', 'funded', '2026-09-03T16:00:00Z'), milestone('repeat', 'l1', 'funded', '2026-09-04T18:00:00Z')); const events = periodEvents(s, ALL_FILTERS).filter(m => m.milestone === 'funded'); expect(events).toHaveLength(2); expect(events.find(m => m.loan_id === 'l1')?.id).toBe('corrected'); expect(periodEvents(s, { ...ALL_FILTERS, from: '2026-09-04', to: '2026-09-04' }).filter(m => m.loan_id === 'l1' && m.milestone === 'funded')).toHaveLength(0); });
    it('keeps unknown commission distinct from zero and excludes plan estimates', () => { const s = fixture(); s.compensation[1].gross_source = 'plan'; const c = cohortMetrics(s, august); expect(c.revenue).toBe(3000); expect(c.revenueKnown).toBe(1); expect(c.revenuePerLead).toBeNull(); s.compensation = []; expect(cohortMetrics(s, august).revenue).toBeNull(); });
    it('selected totals deduplicate loan amounts across repeated rows and follow filters', () => { const s = fixture(), rows = buildRows(s).inquiryRows; const t = rowTotals(s, [...rows, rows[0]]); expect(t.amount).toBe(300000); expect(t.gross).toBe(7000); expect(rowTotals(s, filterRows(rows, { ...ALL_FILTERS, source: 'Referral' })).count).toBe(0); });
    it('source and owner filters change the cohort denominator', () => { const s = fixture(); s.inquiries[1].source = 'Referral'; s.inquiries[1].owner_id = 'other'; expect(cohortMetrics(s, { ...august, source: 'Referral' }).leads).toEqual(['i2']); expect(cohortMetrics(s, { ...august, owner: 'owner' }).leads).toEqual(['i1']); });
    it('does not create an urgent queue from imported contacts or healthy loans', () => { expect(buildRows(fixture()).todayRows).toHaveLength(0); });
    it('routine ownership does not imply Adam needed; explicit escalation does', () => { const s = fixture(); s.tasks = [{ id: 't1', assigned_to: 'owner', status: 'open', related_contact_id: 'c1', title: 'Collect insurance', follow_up_reason: 'waiting:third_party' } as Task]; expect(buildRows(s).todayRows[0]).toMatchObject({ loNeeded: false, waiting: 'third_party' }); s.tasks[0].follow_up_reason = 'escalation:closing_risk'; expect(buildRows(s).todayRows[0].loNeeded).toBe(true); s.tasks[0].is_complete = true; expect(buildRows(s).todayRows).toHaveLength(0); });
    it('uses Central date boundaries and does not count automated confirmations as engagement', () => { expect(day('2026-09-01T03:00:00Z')).toBe('2026-08-31'); const s = fixture(); s.activity = [{ id: 'ack', contact_id: 'c1', loan_id: null, type: 'website_assistant_chat_started', action: 'email.sent', occurred_at: '2026-08-10T16:01:00Z', summary: 'Automated acknowledgment', external_id: null }]; expect(cohortMetrics(s, august).engaged).toHaveLength(0); expect(buildRows(s).inquiryRows[0].lastCommunication).toBeNull(); });
});

describe('operational exceptions and coverage', () => {
    it('shows a current closing risk once beside an existing task without creating tasks', () => { const s=fixture(); s.loans=[{...loan('l1', 100000, 'UNDERWRITING_SUBMITTED'), estimated_closing_date:'2026-09-07'}]; s.tasks=[{id:'t',status:'open',related_loan_id:'l1',assigned_to:'owner',title:'Insurance confirmation',follow_up_reason:'waiting:third_party'} as Task]; const rows=buildRows(s); expect(rows.todayRows).toHaveLength(1); expect(rows.todayRows[0]).toMatchObject({loNeeded:true,waiting:'third_party',deadlineRisk:true}); expect(filterRows(rows.pipelineRows,{...ALL_FILTERS,attention:'lo'})).toHaveLength(1); expect(s.tasks).toHaveLength(1); });
    it('keeps healthy loans and paid commission statuses out of the exception queue',()=>{ const s=fixture(); s.loans=[{...loan('l1', 100000, 'CLEAR_TO_CLOSE'),estimated_closing_date:'2026-09-07',rate_lock_expiration:'2026-10-05'},loan('l2',100000,'Commission Paid')]; expect(buildRows(s).todayRows).toHaveLength(0); expect(buildRows(s).pipelineRows).toHaveLength(1); });
    it('does not use a preapproval or import date for an unrecorded current underwriting stage',()=>{const s=fixture(),l=loan('l1',100000,'UNDERWRITING_SUBMITTED'); expect(loanSignals(s,l).stageDays).toBeNull(); const pre=loan('l1',100000,'PREAPPROVED'); expect(loanSignals(s,pre).stageDays).toBe(0); });
    it('funded period amounts count loans once and exclude loans merely scheduled to close',()=>{const s=fixture();s.loans.push({...loan('l3',900000,'APPROVED_WITH_CONDITION'),closing_date:'2026-09-01'}); const total=fundedPeriodTotals(s,ALL_FILTERS);expect(total.amount).toBe(300000);expect(total.gross).toBe(7000);expect(total.count).toBe(2);});
    it('breaks down a scoped cohort without multiplying opportunities for multiple loans',()=>{const s=fixture();s.inquiries[0].referral_partner='Partner A';s.inquiries[1].referral_partner='Partner B';const g=cohortGroups(s,august,'referral');expect(g.find(x=>x.label==='Partner A')).toMatchObject({leads:1,funded:1,gross:7000,linked:1});expect(cohortGroups(s,{...august,source:'Missing'},'owner')).toHaveLength(0);});
    it('risk totals deduplicate money across tasks and routine waiting does not itself imply risk',()=>{const s=fixture();s.loans=[{...loan('l1',100000,'UNDERWRITING_SUBMITTED'),estimated_closing_date:'2026-09-07'}];s.tasks=[{id:'a',status:'open',related_loan_id:'l1',due_at:'2026-09-01T16:00:00Z'} as Task,{id:'b',status:'open',related_loan_id:'l1',due_at:'2026-09-02T16:00:00Z'} as Task];const m=operationalMetrics(s,buildRows(s).todayRows);expect(m.overdue).toHaveLength(2);expect(m.riskTotals.gross).toBe(3000);expect(m.riskTotals.loans).toBe(1);});
});

it('preserves unlinked general tasks outside the borrower queue',()=>{const s=fixture();s.tasks=[{id:'general',title:'Review website content',source:'manual',status:'open'} as Task];const m=buildRows(s);expect(m.todayRows).toHaveLength(0);expect(m.generalRows).toHaveLength(1);});
