import {describe,it,expect} from 'vitest';
import {createHmac} from 'node:crypto';
import {deskRows,filterDesk,deskTotals,planningAmount,reportingSource,workingStage} from './simple-desk';
import {SITE_SESSION_PATH,verifySiteRequest} from './site-session';
import type {Snapshot} from './types';
const snapshot=():Snapshot=>({asOf:'2026-09-05T17:00:00Z',organizationId:'org',viewerId:'adam',members:[{id:'adam',full_name:'Adam Styer',email:'adam@example.test',role:'owner'}],contacts:[],loans:[],inquiries:[],preferences:[],tasks:[],milestones:[],compensation:[],activity:[],health:[],delivery:[],links:[]});
describe('Simple Lead Desk',()=>{
 it('separates the requested reporting groups without changing source evidence',()=>{expect(reportingSource('Google','',true)).toBe('AI');expect(reportingSource('Website')).toBe('AI');expect(reportingSource('MJ Adams · Realtor referral','',true)).toBe('Realtor Referral');expect(reportingSource('Financial advisor referral','',true)).toBe('Financial Advisor Referral');});
 it('accepts planning amounts while excluding price ranges and unknowns',()=>{expect(planningAmount('$500,000')).toBe(500000);expect(planningAmount('About $1.35M')).toBe(1350000);expect(planningAmount('500K')).toBe(500000);expect(planningAmount('TBD · $500K–$800K price range')).toBeNull();expect(planningAmount('100000-200000')).toBeNull();});
 it('restores saved amounts and named realtors without requiring attribution links',()=>{const s=snapshot();s.preferences=[{id:'saved',contact_id:null,inquiry_id:null,legacy_key:'lead',status:'pre-approved',notes:'Call after work',priority_follow_up:true,amount_note:null,product_note:null,hidden:false,source_updated_at:null,updated_at:'2026-09-04',match_state:'review',provenance:{display_name:'Borrower',restored_lead:{name:'Borrower',source:'MJ Adams · Realtor referral',planning_volume:500000}}} as Snapshot['preferences'][number]];const row=deskRows(s)[0];expect(row.amount).toBe(500000);expect(row.referral).toBe('MJ Adams');expect(row.notes).toBe('Call after work');expect(row.stage).toBe('Pre-approved');expect(deskTotals([row]).compensation).toBe(10000);});
 it('counts a person with multiple inquiries once and includes new incoming people',()=>{const s=snapshot();s.contacts=[{id:'c',first_name:'Alex',last_name:'Test',email:null,phone:null,stage:'lead-contacted',lead_source:'Google',source_page:null,operational_owner_id:'adam'}];const base={contact_id:'c',owner_id:'adam',task_id:null,source:'Google',source_page:null,referral_partner:null,purpose:null,form_name:'contact',legitimacy:'inquiry',is_test:false,match_state:'matched',review_reason:null,parent_inquiry_id:null,provenance:{}};s.inquiries=[{...base,id:'a',received_at:'2026-09-02'},{...base,id:'b',received_at:'2026-09-04'}];const rows=deskRows(s);expect(rows).toHaveLength(1);expect(rows[0].inquiryCount).toBe(2);expect(rows[0].source).toBe('AI');expect(rows[0].stage).toBe('Lead Contacted');});
 it('changes totals with stage, source, hidden, priority, and note/referral search',()=>{const s=snapshot();const mk=(id:string,status:string,amount:string,source:string,notes:string,hidden=false)=>({id,status,amount_note:amount,reporting_source:source,notes,hidden,priority_follow_up:id==='a',provenance:{display_name:id},contact_id:null,inquiry_id:null,legacy_key:id,product_note:null,source_updated_at:null,updated_at:'',match_state:'review'});s.preferences=[mk('a','Lead Contacted','500000','AI','Call Tuesday'),mk('b','Pre-approved','250000','Realtor Referral','Docs done'),mk('c','Lead','900000','AI','Hidden',true)] as Snapshot['preferences'];const rows=deskRows(s);const f={stage:'All',source:'All',query:'',showHidden:false,priorityOnly:false};expect(deskTotals(filterDesk(rows,f))).toMatchObject({count:2,volume:750000,compensation:15000});expect(deskTotals(filterDesk(rows,{...f,stage:'Pre-approved'})).volume).toBe(250000);expect(deskTotals(filterDesk(rows,{...f,source:'AI'})).compensation).toBe(10000);expect(filterDesk(rows,{...f,query:'Tuesday'})).toHaveLength(1);expect(filterDesk(rows,{...f,priorityOnly:true})).toHaveLength(1);});
 it('does not bring historical active-status loans into the working lead list',()=>{const s=snapshot();s.loans=[{id:'old',status:'Application',loan_amount:9000000} as Snapshot['loans'][number]];expect(deskRows(s)).toHaveLength(0);expect(workingStage('loan-in-process')).toBe('Loan in Process');});
});
describe('private Site sign-in connection',()=>{it('rejects forged, expired and modified requests',()=>{const secret='x'.repeat(64),now=Date.now(),body=JSON.stringify({siteUserId:'owner'}),ts=String(now);const signature=createHmac('sha256',secret).update(ts+'\nPOST\n'+SITE_SESSION_PATH+'\n'+body).digest('hex');const req=new Request('https://example.test'+SITE_SESSION_PATH,{method:'POST',headers:{'x-desk-time':ts,'x-desk-signature':signature}});expect(verifySiteRequest(req,body,secret,now)).toBe(true);expect(verifySiteRequest(req,body+' ',secret,now)).toBe(false);expect(verifySiteRequest(req,body,secret,now+61000)).toBe(false);expect(verifySiteRequest(req,body,'wrong',now)).toBe(false);});});
