export type Member = {
    id: string;
    full_name: string | null;
    email: string | null;
    role: string;
};
export type Contact = {
    id: string;
    first_name: string | null;
    last_name: string | null;
    email: string | null;
    phone: string | null;
    stage: string | null;
    lead_source: string | null;
    source_page: string | null;
    operational_owner_id: string | null;
};
export type Loan = {
    id: string;
    contact_id: string | null;
    borrower_first_name: string | null;
    borrower_last_name: string | null;
    loan_name: string | null;
    loan_number: string | null;
    arive_loan_id: string | null;
    status: string | null;
    loan_amount: number | null;
    loan_type: string | null;
    loan_purpose: string | null;
    loan_program: string | null;
    estimated_closing_date: string | null;
    closing_date: string | null;
    rate_lock_expiration: string | null;
    operational_owner_id: string | null;
    processor_name: string | null;
    processor_email: string | null;
    synced_at: string | null;
};
export type Inquiry = {
    id: string;
    contact_id: string | null;
    owner_id: string | null;
    task_id: string | null;
    received_at: string;
    source: string;
    source_page: string | null;
    referral_partner: string | null;
    purpose: string | null;
    form_name: string | null;
    legitimacy: string;
    is_test: boolean;
    match_state: string;
    review_reason: string | null;
    parent_inquiry_id: string | null;
    provenance: Record<string, unknown>;
    displayName?: string;
    email?: string;
    phone?: string;
    first_touch?: Record<string, string>;
    selfReportedSource?: string;
};
export type Task = {
    id: string;
    title: string | null;
    text: string | null;
    description: string | null;
    status: string | null;
    is_complete: boolean | null;
    assigned_to: string | null;
    related_contact_id: string | null;
    related_loan_id: string | null;
    priority: string | null;
    due_at: string | null;
    snoozed_until: string | null;
    follow_up_reason: string | null;
    source: string | null;
    source_key: string | null;
    created_at: string;
};
export type Milestone = {
    id: string;
    inquiry_id: string | null;
    contact_id: string | null;
    loan_id: string | null;
    milestone: string;
    occurred_at: string;
    recorded_at: string;
    source: string;
    source_event_id: string;
    source_url: string | null;
    evidence: Record<string, unknown>;
    voided_at: string | null;
    supersedes_id: string | null;
    outcome_reason: string | null;
};
export type Compensation = {
    loan_id: string;
    gross_source: string;
    gross_comp: number | null;
    net_comp: number | null;
    payout_status: string | null;
};
export type Preference = {
    id: string;
    legacy_key: string | null;
    contact_id: string | null;
    inquiry_id: string | null;
    status: string | null;
    notes: string;
    priority_follow_up: boolean;
    amount_note: string | null;
    product_note: string | null;
    hidden: boolean;
    source_updated_at: string | null;
    updated_at: string;
    match_state: string;
    provenance?: {
        display_name?: string;
        email?: string;
    };
};
export type Activity = {
    id: string;
    contact_id: string | null;
    loan_id: string | null;
    type: string | null;
    action: string | null;
    occurred_at: string | null;
    summary: string | null;
    external_id: string | null;
};
export type SourceHealth = {
    source: string;
    status: string;
    last_success_at: string | null;
    last_event_at: string | null;
    last_attempt_at: string | null;
    detail: string | null;
    inbound: boolean;
    outbound: boolean;
};
export type Delivery = {
    id: string;
    inquiry_id: string;
    kind: string;
    status: string;
    attempts: number;
    created_at: string;
    accepted_at: string | null;
    delivered_at: string | null;
    last_error: string | null;
};
export type LoanLink = {
    id: string;
    inquiry_id: string;
    loan_id: string;
    reviewed_at: string;
    evidence: string;
};
export type Snapshot = {
    ariveFacts?: import('./arive-sync').AriveFact[];
    asOf: string;
    viewerId: string;
    organizationId: string;
    members: Member[];
    contacts: Contact[];
    loans: Loan[];
    inquiries: Inquiry[];
    tasks: Task[];
    milestones: Milestone[];
    compensation: Compensation[];
    preferences: Preference[];
    activity: Activity[];
    health: SourceHealth[];
    delivery: Delivery[];
    links: LoanLink[];
};
export type Filters = {
    owner: string;
    source: string;
    stage: string;
    query: string;
    from: string;
    to: string;
    includeHidden?: boolean;
    attention?: string;
};
export const ALL_FILTERS: Filters = { owner: 'all', source: 'all', stage: 'all', query: '', from: '', to: '' };
export type Row = {
    id: string;
    kind: 'inquiry' | 'loan' | 'task' | 'saved';
    name: string;
    contactId: string | null;
    loanIds: string[];
    inquiryId: string | null;
    taskId: string | null;
    ownerId: string | null;
    owner: string;
    stage: string;
    source: string;
    sourcePage: string | null;
    referral: string | null;
    receivedAt: string | null;
    amount: number | null;
    gross: number | null;
    product: string;
    purpose: string;
    nextAction: string;
    issue: string;
    dueAt: string | null;
    lastCommunication: string | null;
    loNeeded: boolean;
    waiting: string | null;
    email: string | null;
    phone: string | null;
    hidden: boolean;
    preference: Preference | null;
    review: boolean;
    stageSince?: string | null;
    stageDays?: number | null;
    deadlineRisk?: boolean;
    exceptionReasons?: string[];
};
