'use client';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import type {Snapshot} from '@/lib/operations/types';
import {STAGES,SOURCES,deskRows,filterDesk,deskTotals,type DeskRow,type DeskFilters} from '@/lib/operations/simple-desk';
import './simple-desk.css';
const money=(n:number|null)=>n===null?'TBD':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
const columns=['Date','Loan amount','Estimated comp','Product','Source','Referral partner','Status','Notes','Next action','Email','Phone'] as const;
const defaults=columns.filter(c=>!['Date','Product','Email','Phone'].includes(c));
const empty:DeskFilters={stage:'All',source:'All',query:'',showHidden:false,priorityOnly:false};
export default function SimpleLeadDesk({request=fetch}:{request?:typeof fetch}){
 const [data,setData]=useState<Snapshot|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[filters,setFilters]=useState(empty),[selectedId,setSelectedId]=useState<string|null>(null),[shown,setShown]=useState<string[]>([...defaults]),[notice,setNotice]=useState('');
 const [history,setHistory]=useState<{occurred_at?:string;created_at?:string;action?:string;summary?:string;type?:string}[]>([]),[historyError,setHistoryError]=useState('');
 const closeRef=useRef<HTMLButtonElement>(null);
 const refresh=useCallback(async()=>{try{const r=await request('/api/operations',{cache:'no-store'});const j=await r.json();if(!r.ok)throw Error(j.error||'Could not load your leads.');setData(j);setError('');}catch(e){setError(e instanceof Error?e.message:'Could not load your leads.');}},[request]);
 useEffect(()=>{void Promise.resolve().then(refresh);const id=setInterval(()=>{if(!document.hidden)void refresh();},60000);return()=>clearInterval(id);},[refresh]);
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('styer-simple-desk-columns')||'null');if(Array.isArray(saved))queueMicrotask(()=>setShown(saved.filter(c=>columns.includes(c))));}catch{/* Keep default columns if browser preferences are unavailable. */}},[]);
 const rows=useMemo(()=>data?deskRows(data):[],[data]);const visible=useMemo(()=>filterDesk(rows,filters),[rows,filters]);const totals=deskTotals(visible);const selected=rows.find(r=>r.id===selectedId)||null;
 useEffect(()=>{if(!selectedId)return;const previous=document.activeElement as HTMLElement|null;closeRef.current?.focus();const fn=(e:KeyboardEvent)=>{if(e.key==='Escape')setSelectedId(null);if(e.key==='Tab'){const nodes=closeRef.current?.closest('aside')?.querySelectorAll<HTMLElement>('button:not(:disabled),input,textarea,select,summary,a[href]');if(!nodes?.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};document.addEventListener('keydown',fn);return()=>{document.removeEventListener('keydown',fn);if(previous?.isConnected)previous.focus();};},[selectedId]);
 useEffect(()=>{if(!selected?.contactId)return;let active=true;void request('/api/operations/timeline?kind=contact&id='+selected.contactId,{cache:'no-store'}).then(async r=>{const j=await r.json();if(!r.ok)throw Error('Communication history is temporarily unavailable.');if(active)setHistory(j.rows||[]);}).catch(e=>{if(active)setHistoryError(e.message);});return()=>{active=false;};},[selected?.contactId,request]);
 async function save(row:DeskRow,patch:Record<string,unknown>){setBusy(true);setNotice('');try{const target=row.preference?.id||row.contactId;if(!target)throw Error('This inquiry needs its identity reviewed before saving.');const r=await request('/api/operations/preferences/'+target+(row.preference?'':'?contact=true'),{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(patch)});const j=await r.json();if(!r.ok)throw Error(j.error||'Your changes were not saved.');await refresh();if(selectedId===row.id)setSelectedId(j.id);setNotice('Saved.');}catch(e){setError(e instanceof Error?e.message:'Your changes were not saved.');}finally{setBusy(false);}}
 function openLead(id:string){setHistory([]);setHistoryError('');setSelectedId(id);}
 const toggleColumn=(column:string)=>{const next=shown.includes(column)?shown.filter(c=>c!==column):[...shown,column];setShown(next);localStorage.setItem('styer-simple-desk-columns',JSON.stringify(next));};
 const stageCounts=(stage:string)=>filterDesk(rows,{...filters,stage}).length;
 function cell(row:DeskRow,column:string){switch(column){case 'Date':return row.receivedAt?new Date(row.receivedAt).toLocaleDateString('en-US',{month:'short',day:'numeric'}):'—';case 'Loan amount':return money(row.amount);case 'Estimated comp':return money(row.amount===null?null:row.amount*.02);case 'Product':return row.product||'TBD';case 'Source':return row.source;case 'Referral partner':return row.referral||(['Realtor Referral','Financial Advisor Referral'].includes(row.source)?'Add referral name':'—');case 'Status':return <select aria-label={'Status for '+row.name} value={row.stage} disabled={busy} onChange={e=>void save(row,{status:e.target.value})}>{STAGES.map(s=><option key={s}>{s}</option>)}</select>;case 'Notes':return <button className="desk-note" onClick={()=>openLead(row.id)}>{row.notes||row.context||'Add notes'}</button>;case 'Next action':return <button className="desk-note" onClick={()=>openLead(row.id)}>{row.nextAction||'Add next action'}</button>;case 'Email':return row.email||'—';case 'Phone':return row.phone||'—';}}
 return <main className="simple-desk"><header className="desk-header"><div><span className="desk-eyebrow">THE STYER TEAM</span><h1>Lead Desk</h1></div><div className="desk-account">Adam Styer · All work assigned to you{data&&<small>Updated {new Date(data.asOf).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'})}</small>}<button onClick={()=>void refresh()} disabled={busy}>Refresh</button></div></header>
 {error&&<div className="desk-error" role="alert">{error} <button onClick={()=>void refresh()}>Try again</button></div>}{notice&&<p role="status" className="desk-notice">{notice}</p>}
 {!data?<p role="status" className="desk-loading">Loading your leads…</p>:<>
 <div className="desk-toolbar"><label className="desk-search">Search<input value={filters.query} onChange={e=>setFilters({...filters,query:e.target.value})} placeholder="Name, notes, realtor, or advisor"/></label><label>Lead source<select value={filters.source} onChange={e=>setFilters({...filters,source:e.target.value})}><option value="All">All sources</option>{SOURCES.map(s=><option key={s}>{s}</option>)}</select></label><details className="desk-columns"><summary>Columns</summary>{columns.map(c=><label key={c}><input type="checkbox" checked={shown.includes(c)} onChange={()=>toggleColumn(c)}/>{c}</label>)}</details><label className="desk-check"><input type="checkbox" checked={filters.priorityOnly} onChange={e=>setFilters({...filters,priorityOnly:e.target.checked})}/>Priority only</label><label className="desk-check"><input type="checkbox" checked={filters.showHidden} onChange={e=>setFilters({...filters,showHidden:e.target.checked})}/>Show hidden</label></div>
 <nav className="desk-stages" aria-label="Lead views">{['All',...STAGES].map(s=><button key={s} className={filters.stage===s?'active':''} aria-pressed={filters.stage===s} onClick={()=>setFilters({...filters,stage:s})}>{s}<span>{stageCounts(s)}</span></button>)}</nav>
 <section className="desk-totals" aria-label="Totals for selected leads"><div><small>{filters.stage==='All'?'LEADS IN THIS VIEW':filters.stage.toUpperCase()}</small><strong>{totals.count}</strong><span>{filters.source==='All'?'All sources':filters.source}</span></div><div><small>LOAN VOLUME</small><strong>{money(totals.volume)}</strong><span>{totals.known} amounts · {totals.tbd} TBD</span></div><div><small>ESTIMATED COMPENSATION · 2%</small><strong>{money(totals.compensation)}</strong><span>Planning estimate</span></div><div><small>AVERAGE KNOWN LOAN</small><strong>{money(totals.average)}</strong><span>Selected leads with an amount</span></div></section>
 <div className="desk-table-wrap"><table><thead><tr><th scope="col">Lead</th><th scope="col">Priority</th>{columns.filter(c=>shown.includes(c)).map(c=><th scope="col" key={c}>{c}</th>)}</tr></thead><tbody>{visible.map(row=><tr key={row.id} className={row.hidden?'desk-hidden':''}><th scope="row"><button className="desk-name" onClick={()=>openLead(row.id)}>{row.name}</button>{row.inquiryCount>1&&<small>{row.inquiryCount} inquiries · counted once</small>}</th><td><button className={row.priority?'desk-star active':'desk-star'} aria-label={'Priority for '+row.name} aria-pressed={row.priority} disabled={busy} onClick={()=>void save(row,{priority_follow_up:!row.priority})}>{row.priority?'★':'☆'}</button></td>{columns.filter(c=>shown.includes(c)).map(c=><td key={c}>{cell(row,c)}</td>)}</tr>)}</tbody></table>{!visible.length&&<p className="desk-empty">No leads match this view. <button onClick={()=>setFilters(empty)}>Clear filters</button></p>}</div><p className="desk-footnote">Totals follow your view and search. Compensation is 2% of the selected loan volume; actual earnings may differ.</p>
 </>}
 {selected&&<div className="desk-overlay"><aside role="dialog" aria-modal="true" aria-labelledby="desk-lead-title"><button className="desk-close" ref={closeRef} onClick={()=>setSelectedId(null)} aria-label="Close lead details">×</button><h2 id="desk-lead-title">{selected.name}</h2><p>Assigned to Adam Styer</p><p>{selected.email}{selected.email&&selected.phone?' · ':''}{selected.phone}</p><form key={selected.id+'-'+selected.preference?.updated_at} onSubmit={e=>{e.preventDefault();const fd=new FormData(e.currentTarget);void save(selected,{status:fd.get('status'),reporting_source:fd.get('source'),referral_name:fd.get('referral'),amount_note:fd.get('amount'),product_note:fd.get('product'),notes:fd.get('notes'),next_action:fd.get('action'),priority_follow_up:fd.get('priority')==='on',hidden:fd.get('hidden')==='on'});}}><label>Status<select name="status" defaultValue={selected.stage}>{STAGES.map(s=><option key={s}>{s}</option>)}</select></label><label>Lead source<select name="source" defaultValue={selected.source}>{SOURCES.map(s=><option key={s}>{s}</option>)}</select></label><label>Realtor / financial advisor / referral name<input name="referral" maxLength={300} defaultValue={selected.referral}/></label><div className="desk-two"><label>Loan amount for planning<input name="amount" maxLength={200} defaultValue={selected.amount===null?selected.amountText:money(selected.amount)} placeholder="TBD"/></label><label>Estimated compensation<strong>{money(selected.amount===null?null:selected.amount*.02)}</strong><small>2% of loan amount</small></label></div><label>Product<input name="product" maxLength={500} defaultValue={selected.product}/></label><label>Next action<textarea name="action" maxLength={2000} defaultValue={selected.nextAction}/></label><label>Your notes<textarea className="desk-notes-input" name="notes" maxLength={10000} defaultValue={selected.notes}/></label><label className="desk-check"><input name="priority" type="checkbox" defaultChecked={selected.priority}/>Priority follow-up</label><label className="desk-check"><input name="hidden" type="checkbox" defaultChecked={selected.hidden}/>Hide from normal views</label><button className="desk-save" disabled={busy}>{busy?'Saving…':'Save changes'}</button></form>{selected.context&&<section><h3>Existing notes and scenario</h3><p className="desk-context">{selected.context}</p></section>}<section><h3>Communication history</h3>{historyError?<p>{historyError}</p>:history.length?history.slice(0,30).map((h,i)=><div className="desk-history" key={i}><small>{(h.occurred_at||h.created_at)?new Date((h.occurred_at||h.created_at)!).toLocaleString():'Date not recorded'}</small><p>{h.action||h.type}</p>{h.summary&&<p>{h.summary}</p>}</div>):<p>No linked communication history available.</p>}</section><details><summary>Original source details</summary><p>{selected.originalSource}</p><p>AI is your reporting group for website leads. Original acquisition details are retained.</p></details></aside></div>}
 </main>;
}
