'use client'
import {useEffect,useMemo,useState} from 'react'
import Link from 'next/link'
import SignOutButton from '@/app/dashboard/SignOutButton'
import type {TeamKind,TeamRecord,TeamSnapshot} from '@/lib/team/types'
import {STAGES,SOURCES} from '@/lib/operations/simple-desk'
import './team.css'
const money=(v:number|null)=>v===null?'TBD':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(v)
export default function TeamDesk(){
 const [data,setData]=useState<TeamSnapshot|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const [kind,setKind]=useState<TeamKind>('lead'),[stage,setStage]=useState('All'),[query,setQuery]=useState(''),[selected,setSelected]=useState<string|null>(null),[limit,setLimit]=useState(100)
 async function refresh(){const r=await fetch('/api/team',{cache:'no-store'});const j=await r.json();if(!r.ok)throw Error(j.error||'Unable to load');setData(j);setError('')}
 useEffect(()=>{void refresh().catch(e=>setError(e.message))},[])
 const rows=useMemo(()=>data?.records.filter(r=>r.kind===kind&&(stage==='All'||r.stage===stage)&&(!query||[r.name,r.email,r.phone,r.referral,r.product].join(' ').toLowerCase().includes(query.toLowerCase())))||[],[data,kind,stage,query])
 const record=data?.records.find(r=>r.id===selected&&r.kind===kind)
 const amountRows=rows.filter(r=>r.amount!==null)
 const volume=amountRows.reduce((s,r)=>s+r.amount!,0),comp=amountRows.reduce((s,r)=>s+(r.ownCompensation||0),0)
 useEffect(()=>{setLimit(100)},[kind,stage,query])
 useEffect(()=>{if(!selected)return;document.querySelector<HTMLElement>('.team-detail')?.focus({preventScroll:true});document.querySelector('.team-detail')?.scrollIntoView({behavior:'smooth',block:'start'});const f=(e:KeyboardEvent)=>{if(e.key==='Escape')setSelected(null)};window.addEventListener('keydown',f);return()=>window.removeEventListener('keydown',f)},[selected])
 async function save(payload:Record<string,unknown>){setBusy(true);setError('');try{const r=await fetch('/api/team',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const j=await r.json();if(!r.ok)throw Error(j.error);await refresh();return true}catch(e){setError(e instanceof Error?e.message:'Unable to save');return false}finally{setBusy(false)}}
 function exportRows(){const cell=(v:unknown)=>{const s=String(v??'');return '"'+(/^[=+\-@\t\r]/.test(s)?"'"+s:s).replace(/"/g,'""')+'"'};const csv=[['Name','Stage','Email','Phone','Loan amount','Your estimated compensation','Your basis points'],...rows.map(r=>[r.name,r.stage,r.email,r.phone,r.amount,r.ownCompensation,data?.compBps])].map(r=>r.map(cell).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`loanos-${kind}.csv`;a.click();URL.revokeObjectURL(url)}
 return <div className="team-desk"><header className="team-header"><Link href="/team" className="team-brand">LoanOS</Link><span>Team workspace</span><div className="team-account">{data?.displayName}{data?.owner&&<Link href="/dashboard">My dashboard</Link>}<SignOutButton/></div></header><main>
 <div className="team-title"><div><p className="team-eyebrow">YOUR WORKDAY</p><h1>{kind==='lead'?'Lead Desk':kind==='loan'?'Loan records':'Contact records'}</h1><p>Shared records, clear next steps, and your compensation.</p></div><button onClick={()=>void refresh().catch(e=>setError(e.message))}>Refresh</button></div>
 <nav className="team-tabs" aria-label="Records">{(['lead','loan','contact'] as TeamKind[]).map(k=><button key={k} aria-pressed={kind===k} onClick={()=>{setKind(k);setStage('All');setSelected(null)}}>{k==='lead'?'Leads':k==='loan'?'Loans':'Contacts'}</button>)}</nav>
 {error&&<div className="team-error" role="alert">{error}</div>}
 {!data?<p>{error?'Workspace unavailable.':'Loading your workspace…'}</p>:<><section className="team-totals" aria-label="Totals for this view"><div><small>RECORDS IN THIS VIEW</small><strong>{rows.length.toLocaleString()}</strong></div>{kind!=='contact'&&<><div><small>LOAN VOLUME</small><strong>{money(volume)}</strong><span>{rows.length-amountRows.length} amounts TBD</span></div><div><small>YOUR ESTIMATED COMPENSATION · {data.compBps} BPS</small><strong>{money(comp)}</strong><span>{data.compBps/100}% of loan amount · planning estimate</span></div></>}</section>
 <div className="team-filters"><label>Search<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name, email, referral…"/></label><label>Stage<select value={stage} onChange={e=>setStage(e.target.value)}><option>All</option>{STAGES.map(s=><option key={s}>{s}</option>)}</select></label><button onClick={exportRows}>Export this view</button></div>
 <div className="team-table-wrap"><table><thead><tr><th>Name</th><th>Stage</th><th>{kind==='contact'?'Email':'Loan amount'}</th>{kind!=='contact'&&<th>Your estimated compensation</th>}<th>{kind==='lead'?'Referral':'Product'}</th></tr></thead><tbody>{rows.slice(0,limit).map(r=><tr key={r.kind+r.id}><td><button className="team-record-link" onClick={()=>setSelected(r.id)}>{r.priority?'★ ':''}{r.name}</button><small>{r.phone}</small></td><td>{r.stage}</td><td>{kind==='contact'?r.email:money(r.amount)}</td>{kind!=='contact'&&<td>{money(r.ownCompensation)}</td>}<td>{kind==='lead'?r.referral||'—':r.product||'—'}</td></tr>)}</tbody></table>{rows.length===0&&<p className="team-empty">No records match this view.</p>}</div>{limit<rows.length&&<button onClick={()=>setLimit(limit+100)}>Show more ({rows.length-limit} remaining)</button>}<p className="team-updated">Updated {new Date(data.asOf).toLocaleString()}. Compensation figures are estimates, not payments received.</p></>}
 {record&&data&&<section className="team-detail" tabIndex={-1} aria-label={`${record.name} details`}><button className="team-close" onClick={()=>setSelected(null)}>Close details</button><h2>{record.name}</h2><p>{record.email&&<a href={`mailto:${record.email}`}>{record.email}</a>}{record.email&&record.phone?' · ':''}{record.phone&&<a href={`tel:${record.phone}`}>{record.phone}</a>}</p>{kind!=='contact'&&<p>Loan amount: <strong>{money(record.amount)}</strong> · Your estimate: <strong>{money(record.ownCompensation)}</strong> ({data.compBps} bps)</p>}{record.closingDate&&<p>Closing date: {record.closingDate}</p>}{record.ariveOwned&&<p>Loan facts are synced from ARIVE.</p>}
 {kind!=='loan'&&<RecordForm key={kind+record.id+data.asOf} record={record} busy={busy} onSave={changes=>save({id:record.id,kind,changes})}/>}
 <h3>Shared team notes</h3><p className="team-note-help">Notes added here are visible to your team. Historical private notes and original documents are not included.</p><form onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const note=String(new FormData(form).get('note')||'');if(await save({id:record.id,kind,note}))form.reset()}}><label>Add a note or next step<textarea name="note" required maxLength={10000}/></label><button disabled={busy}>Add shared note</button></form>{data.notes.filter(n=>n.record_id===record.id&&n.record_kind===kind).sort((a,b)=>b.created_at.localeCompare(a.created_at)).map(n=><article className="team-note" key={n.id}><small>{n.author_name} · {new Date(n.created_at).toLocaleString()}</small><p>{n.body}</p></article>)}</section>}
 </main></div>
}
function RecordForm({record:r,busy,onSave}:{record:TeamRecord;busy:boolean;onSave:(changes:Record<string,unknown>)=>Promise<boolean>}){
 return <form className="team-edit" onSubmit={e=>{e.preventDefault();const fd=new FormData(e.currentTarget);const changes=Object.fromEntries(fd);void onSave(r.kind==='lead'?{...changes,priority_follow_up:fd.get('priority_follow_up')==='on'}:changes)}}>
 {r.kind==='contact'?<><label>Email<input name="email" type="email" defaultValue={r.email}/></label><label>Phone<input name="phone" defaultValue={r.phone}/></label><label>Stage<select name="stage" defaultValue={r.stage}>{STAGES.map(s=><option key={s}>{s}</option>)}</select></label></>:<><label>Stage<select name="status" disabled={r.ariveOwned} defaultValue={r.stage}>{STAGES.map(s=><option key={s}>{s}</option>)}</select></label><label>Loan amount<input name="amount_note" type="number" min="0.01" step="0.01" disabled={r.ariveOwned} defaultValue={r.amount??''} placeholder="TBD"/></label><label>Product<input name="product_note" disabled={r.ariveOwned} defaultValue={r.product} maxLength={500}/></label><label>Source<select name="reporting_source" defaultValue={r.source}>{SOURCES.map(s=><option key={s}>{s}</option>)}</select></label><label>Referral name<input name="referral_name" defaultValue={r.referral} maxLength={500}/></label><label className="team-check"><input name="priority_follow_up" type="checkbox" defaultChecked={r.priority}/>Priority follow-up</label></>}
 <button disabled={busy}>Save changes</button></form>
}
